<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>*</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>monitrc</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+%?</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>constant.character.brace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>constant.character.paren</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"(.*)\"</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\d\w_\-.]+@[\d\w_\-.]+</string>
			<key>name</key>
			<string>string.email</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\'(.*)\'</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|and)\b</string>
			<key>name</key>
			<string>keyword.control.monit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(&gt;|&lt;)\b</string>
			<key>name</key>
			<string>keyword.operator.monit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(set|check|include)\b</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(pidfile|path|alert|noalert|system|logfile|group|failed|port|checksum|start|stop|restart|program|daemon|space|usage|timeout|restarts|within|cycles|depends|type|proto|protocol|logfile|syslog|address|enable|disable|pemfile|allow|read-only|check|init|count|pidfile|statefile|group|start|stop|uid|gid|connection|port|portnumber|unix|unixsocket|mail-format|resource|expect|send|mailserver|every|mode|active|passive|manual|depends|host|default|request|cpu|mem|totalmem|children|loadavg|timestamp|changed|second|seconds|minute|minutes|hour|hours|day|days|inode|pid|ppid|perm|permission|icmp|process|file|directory|filesystem|size|action|unmonitor|rdate|rsync|data|invalid|exec|nonexist|policy|reminder|instance|eventqueue|basedir|slot|slots|system|idfile|gps|radius|secret|target|maxforward|hostheader|url)\b</string>
			<key>name</key>
			<string>constant.language.monit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/.*</string>
			<key>name</key>
			<string>entity.name.filepath</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-z]+:\/.+</string>
			<key>name</key>
			<string>entity.name.url</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(md5|sha1)\b</string>
			<key>name</key>
			<string>entity.name.checksum</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(tcp|udp|tcpssl)\b</string>
			<key>name</key>
			<string>entity.name.socket</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(https|ssl|http|ftp|smtp|pop|ntp3|nntp|imap|clamav|ssh|dwp|ldap2|ldap3|tns)\b</string>
			<key>name</key>
			<string>entity.name.protocol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>a-zA-Z0-9\-\.+</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(device|with|times|for|cycles)\b</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.monitrc</string>
	<key>uuid</key>
	<string>2550FA4F-F9D6-4423-8C95-695339BBDC62</string>
</dict>
</plist>